- .nuget/packages.config
`NUnit.Runner` is required to run the test. Currently it'll work on AppVeyor since AppVeyor has NUnit.Runner built in.
> Add NUnit.Runnner to required NuGet packages

- Parse/ParseUser.cs
Because this task wasn't properly unwrapped, 'OnSuccess' was always being invoked, as the task was techincally successful. This caused a regression, where we always would set the current user to be this object, even if an error occured during save.
Fixes #10.
cc @hallucinogen @grantland
> Properly unwrap tasks returned during signup.

- Parse/PlatformHooks.Unity.cs
`UnityEngine.Application` only lets some of their properties be get from main thread. Those values can be cached and used later time. This PR will fix issue #7
@grantland @nlutsenko @wangmengyan95
> Fix Unity properties initialization

- Parse/Internal/HttpClient.Unity.cs
When unity has no network, it returns an empty string for 'error', which causes `Int32.Parse` to throw an exception.
Fixes #20.
cc @hallucinogen @grantland
> Parse error codes from unity using TryParse, to prevent exceptions.

- Parse/PlatformHooks.WinRT.cs
This could happen because by default, `await` continues on the thread it was invoked from, in this case, the main thread, which is blocked on the line below.
Fixes #26.
cc @hallucinogen @grantland
> Fix deadlock in WinRT platform utils when AppName is accessed from the main thread.

- Parse/ParsePush.WinRT.cs
When a push was received without a handler, we would previously crash. This doesn't exist as an issue on other platforms, as we use other notification delivery systems there.
Fixes #27.
cc @hallucinogen @grantland
> Fix NullReferenceException when push notification handler hasn't been registered.

- Parse/ParseObject.cs
When saving a ParseObject which had the same object reference inside of itself twice (which is a supported use-case), we would crash because .NET's dictionary implementation does throws an exception when attempting to overwrite a key.
Fixes #29.
cc @grantland @hallucinogen
> Fix crash related to duplicate dictionary keys.

- Parse/Properties/SharedAssemblyInfo.cs
> SDK Version 1.6.1 Release.

- Parse/Internal/ManifestInfo.cs
- Parse/ParsePush.Android.cs
This brings us up to parity with the main Parse android SDK: https://parse.com/tutorials/android-push-notifications.
Fixes #39.
> Support custom push notification icon in Xamarin android.

- Parse/PlatformHooks.Unity.cs
Push notifications on Unity 5 were broken due to IL2CPP not supporting PropertyInfo being exported by any type.
Fixes #36.
> Drop support for Unity 4, to support push notifications.

- Parse/ParseQuery.cs
- Parse/ParseRelation.cs
- ParseTest.Unit/ParseTest.Unit.NetFx45.csproj
- ParseTest.Unit/RelationTests.cs
This is useful for creating a relation client-side when previously one did not exist.
Fixes #72.
> Add support for redirecting class-names of ParseRelations.

- Parse/Compat/Tuple.cs
- Parse/Compat/Type.cs
- Parse/Internal/Object/Subclassing/IObjectSubclassingController.cs
- Parse/Internal/Object/Subclassing/ObjectSubclassInfo.cs
- Parse/Internal/Object/Subclassing/ObjectSubclassingController.cs
- Parse/Internal/ParseCorePlugins.cs
- Parse/Internal/ReflectionHelpers.cs
- Parse/Parse.Android.csproj
- Parse/Parse.Unity.csproj
- Parse/Parse.csproj
- Parse/Parse.iOS.csproj
- Parse/ParseObject.cs
- Parse/ParseQuery.cs
- Parse/ParseRelation.cs
- ParseTest.Unit/CurrentInstallationControllerTests.cs
- ParseTest.Unit/CurrentUserControllerTests.cs
- ParseTest.Unit/InstallationTests.cs
- ParseTest.Unit/SessionTests.cs
- ParseTest.Unit/UserTests.cs
Similar to the subclassing architecture used on iOS, this abstracts and cleans up all of the code relating to subclassing that currently resides inside of ParseObject.
Tests coming soon™.
> Decoupled ParseObject subclassing

- Parse/Internal/Analytics/Controller/ParseAnalyticsController.cs
- Parse/Internal/Cloud/Controller/ParseCloudCodeController.cs
- Parse/Internal/Command/ParseCommand.cs
- Parse/Internal/Config/Controller/ParseConfigController.cs
- Parse/Internal/File/Controller/ParseFileController.cs
- Parse/Internal/HttpRequest.cs
- Parse/Internal/Object/Controller/ParseObjectController.cs
- Parse/Internal/Push/Controller/ParsePushController.cs
- Parse/Internal/Query/Controller/ParseQueryController.cs
- Parse/Internal/Session/Controller/ParseSessionController.cs
- Parse/Internal/User/Controller/ParseUserController.cs
- Parse/ParseClient.cs
- ParseTest.Unit/AnalyticsControllerTests.cs
- ParseTest.Unit/CommandTests.cs
- ParseTest.Unit/ObjectControllerTests.cs
- ParseTest.Unit/SessionControllerTests.cs
- ParseTest.Unit/UserControllerTests.cs
This allows us to more easily do path redirection while performing tests.
Also: Make batch requests no longer require manual encoding.
Now leverages the existing 'ParseCommand' class instead of constructing improperly typed dictionaries.
> Remove hard-coded '/1/' from all API request URIs.

- Parse/Internal/HttpClient.Android.cs
- Parse/Internal/HttpClient.NetFx45.cs
- Parse/Internal/HttpClient.Phone.cs
- Parse/Internal/HttpClient.WinRT.cs
- Parse/Internal/HttpClient.iOS.cs
This was causing errors to happen at certain parts of the process to be discarded, leading to crashes because we never read from the Task.Exception.
Fixes #81.
> Fix several continuations inside of HttpClient.

- Parse/Internal/File/State/FileState.cs
If you accessed `file.Url` without being saved yet, you would crash. Very bad.
> Fix potential NullPointerException in FileState.

- Parse/ParseObject.cs
This would cause issues when updating an installation. By forcing removal of a key using an operation, we no longer check for children who override `IsMutableForKey`.
Fixes #40, and probably several others.
cc @grantland @hallucinogen
> Make `SetIfDifferent` no longer check if a key is mutable.

- Parse/Internal/Push/Coder/ParsePushEncoder.cs
- Parse/Internal/Push/State/IPushState.cs
- Parse/Internal/Push/State/MutablePushState.cs
- Parse/ParsePush.cs
Hello,
This changed add the possibility to specify PushTime properties in ParsePush instance to be able to send delayed notifications.
> Implement support to send delayed push notification using .NET SDK.

- Parse/Internal/FacebookAuthenticationProvider.cs
Passing null 'Method' causes ArgumentException (Cannot set null or blank methods on request) so ParseFacebookUtils doesn't work at all.
> FacebookAuthenticationProvider.cs fix

- ParsePush/src/main/java/com/parse/ParsePushService.java
> [Unity] Fix crash in ParsePush.jar related to empty push payload.

- Parse/Internal/FacebookAuthenticationProvider.cs
- Parse/Internal/Installation/Controller/ParseCurrentInstallationController.cs
- Parse/Internal/ParseDecoder.cs
- Parse/Internal/ParseEncoder.cs
- Parse/Internal/User/Controller/ParseCurrentUserController.cs
- Parse/ParseClient.cs
- ParseTest.Unit/DecoderTests.cs
This was causing sporadic issues when the server returns dates that are valid according to the ISO standard, but not according to DateTime.ParseExact.
Fixes #64.
> Support any number of trailing zeroes when decoding dates.

- .editorconfig
- CONTRIBUTING.md
This allows for a consistent, cross-platform approach to at least handle line endings and newlines+spaces.
Depends on #96.
> Added editorconfig file.

- Parse/Internal/Json.cs
Found another typo of the word support.  Surprised I missed it last time!
> [Typo] Fixes typo in Parse/Internal/Json.cs

- Parse/Internal/ReflectionHelpers.cs
`GetConstructors()` does not find private constructors by default, causing us to be unable to find the constructor of `ParseObject` when running in the context of Unity.
Fixes #111.
> Fix constructor detection on Unity.

- Parse/Internal/Json.cs
- Parse/Internal/Object/Subclassing/ObjectSubclassInfo.cs
- Parse/Internal/ParseEncoder.cs
- Parse/Internal/ReflectionHelpers.cs
- Parse/ParseClient.cs
- Parse/ParseConfig.cs
- Parse/ParseObject.cs
- Parse/ParseQueryExtensions.cs
Reason: as we start adding support for more platforms which may or may not have this natively, our extension methods are not guaranteed to be invoked if they have the same name of a builtin method.
My requiring explicit invoking, it allows us to enforce custom logic here.
Fixes #111 (for real this time).
> Made all methods in ReflectionHelpers non-extensions.

- Parse/Internal/Command/ParseCommand.cs
- Parse/Public/ParseClient.cs
Proposing a new initialization API, to allow for more flexibility and clarity in the future:
````csharp
ParseClient.Initialize(new ParseClient.Configuration {
ApplicationId = ...,
WindowsKey = ...
});
````
No APIs are being directly deprecated at this time, only additions for the time being.
-----------
This PR hopes to unify some of these initialization settings int o a single 'configuration' class that can be easily used to intialize parse in a much cleaner way, especially as we add even more initialization options.
Depends on #77.
> Add better, more flexible APIs for SDK initialization.

- Parse/Internal/Config/Controller/IParseConfigController.cs
- Parse/Internal/HttpClient/NetFx45/HttpClient.NetFx45.cs
- Parse/Internal/HttpClient/Phone/HttpClient.Phone.cs
- Parse/Internal/HttpClient/WinRT/HttpClient.WinRT.cs
- Parse/Internal/HttpClient/iOS/HttpClient.iOS.cs
- Parse/Internal/Installation/Controller/IInstallationIdController.cs
- Parse/Internal/PlatformHooks/Phone/PlatformHooks.Phone.cs
- Parse/Internal/PlatformHooks/WinRT/PlatformHooks.WinRT.cs
- Parse/Internal/PlatformHooks/iOS/PlatformHooks.iOS.cs
- Parse/Internal/Utilities/Json.cs
- Parse/Public/ParseClient.cs
- Parse/Public/ParseExtensions.cs
- Parse/Public/ParseInstallation.cs
- Parse/Public/Partial/ParsePush.cs
- Parse/Public/Phone/ParseFacebookUtils.Phone.cs
- Parse/Public/Unity/ParseInitializeBehaviour.cs
- Parse/Public/WinRT/ParsePush.WinRT.cs
Mostly super minor mistakes in documentation.
> Fix minor typos throughout the SDK.

- Parse/Parse.NetFx45.csproj
- Parse/Parse.Phone.csproj
- Parse/Parse.WinRT.csproj
- Parse/Parse.csproj
- Parse/Properties/AssemblyInfo.Portable.cs
Yet another pull request to prepare us to sign the `.dll`s. Also cleanup legacy code from `Parse/Properties/AssemblyInfo.Portable.cs`
> Prepare .csproj for code signing

- Parse/Internal/Command/ParseCommand.cs
- Parse/Internal/HttpClient/Android/HttpClient.Android.cs
- Parse/Internal/HttpClient/NetFx45/HttpClient.NetFx45.cs
- Parse/Internal/HttpClient/Phone/HttpClient.Phone.cs
- Parse/Internal/HttpClient/WinRT/HttpClient.WinRT.cs
- Parse/Internal/HttpClient/iOS/HttpClient.iOS.cs
Our internal integration tests was broken. This will fix it.
For the case of `HttpClient`, we can't do `OnSuccess`. If you take a look inside the code, we do special handling on error.
> Fix internal IntegrationTests

- Parse/Internal/Encoding/ParseDecoder.cs
- Parse/Internal/Installation/Controller/ParseCurrentInstallationController.cs
- Parse/Internal/User/Controller/ParseCurrentUserController.cs
- Parse/Public/ParseSession.cs
- Parse/Public/ParseUser.cs
We have `FromState` which wraps `CreateWithoutData` + `HandleFetchResult`. This is just a convenience method that's also used in Android SDK.
Tested with Unit Test
> Use `FromState` instead of `CreateWithoutData` + `HandleFetchResult`

- Parse/Internal/PlatformHooks/Phone/PlatformHooks.Phone.cs
- Parse/Internal/PlatformHooks/Unity/PlatformHooks.Unity.cs
Previously, TimeZone string generation that we sent along with ParseInstallation was dependent upon the `CurrentCulture` of the device being set to the english locale (as `StandardName` is localized, WHAT?!)
Our new, fancy TimeZone string is now generated agnostically of the current device locale. There is potential for information about the specific region of the time zone to be lost here, but most applications
should not require this.
This should fix #138.
> Made TimeZone string generation locale-agnostic for Windows Phone and Unity.

- Parse/Internal/PlatformHooks/Phone/PlatformHooks.Phone.cs
- Parse/Internal/PlatformHooks/Unity/PlatformHooks.Unity.cs
Reverts ParsePlatform/Parse-SDK-dotNET#145
This fix wasn't working with our backend properly :cry:
> Revert "Made TimeZone string generation locale-agnostic for Windows Phone and Unity."

- Parse/Internal/PlatformHooks/Phone/PlatformHooks.Phone.cs
- Parse/Internal/PlatformHooks/Unity/PlatformHooks.Unity.cs
- Parse/Public/ParseInstallation.cs
This was causing installation saves to fail when not on english locale.
For real, this time.
Fixes #138.
> Fix TimeZone mappings for Windows Phone and Unity

- ParseCore/Internal/Encoding/ParseEncoder.cs
- ParseCore/Internal/User/Controller/ParseCurrentUserController.cs
This allows dates in Arabic/Thai locales to be entered correctly in parse.
> Use the InvariantCulture to format DateTime.

- ParsePush/Native/src/main/java/com/parse/ParsePushService.java
I think "com.parse.push.gcm_sender_id" value should be start with "id:".
> Fix contitional judgment for gcm_sender_id value

- ParseCore/Internal/Command/ParseCommand.cs
When ParseFile.SaveAsync is called the request will be initially directed to ParseCommandRunner, which will add necessary header attributes and execute the request. RunCommandAsync calls PrepareCommand, which clones the original command into new one
`ParseCommand newCommand = new ParseCommand(command);`
When you go to the implementation of clone constructor you'll see that all fields are cloned, except the Data field, which cause all file uploads fail with "Invalid File upload" message.
> Fixed minor bug which was causing failing ParseFile uploads.

- README.md
I did this on the README because it took me a lot of time to figure out how to initialize the ParseClient with a custom server url.
> Added initialization code for hosted Parse on the README

- ParsePush/Native/src/main/java/com/parse/ManifestInfo.java
From documentation (https://github.com/ParsePlatform/parse-server/wiki/Push-Configuring-Clients#configure-broadcast-receiver-and-permissions), GET_ACCOUNTS is only required for GCM on devices running Android lower than 4.0.4.
I think it should be optional.
> Removed android.permission.GET_ACCOUNTS from required permissions.

- README.md
Switches to using the official **ParseCommunity** account on appveyor.
> Use ParseCommunity on Appveyor

- .gitignore
- Unity.Tasks.TypeForwards/Properties/AssemblyInfo.cs
- Unity.Tasks.TypeForwards/Public/TaskTypeForwards.cs
- Unity.Tasks.TypeForwards/Unity.Tasks.TypeForwards.csproj
- Unity.Tasks.UnityPlugin/Properties/AssemblyInfo.cs
- Unity.Tasks.UnityPlugin/Unity.Tasks.UnityPlugin.csproj
- Unity.Tasks.UnityPlugin/UnityProjectTemplate/Assets/Parse.meta
- Unity.Tasks.UnityPlugin/UnityProjectTemplate/Assets/Parse/Plugins.meta
- Unity.Tasks.UnityPlugin/UnityProjectTemplate/Assets/Parse/Plugins/Unity.Compat.dll.meta
- Unity.Tasks.UnityPlugin/UnityProjectTemplate/Assets/Parse/Plugins/Unity.Tasks.dll.meta
- Unity.Tasks.UnityPlugin/UnityProjectTemplate/Assets/Parse/Plugins/dotNet45.meta
- Unity.Tasks.UnityPlugin/UnityProjectTemplate/Assets/Parse/Plugins/dotNet45/Unity.Tasks.dll.meta
This patch introduces:
* Type forwarding DLL for Parse implementation of System.Threading.Tasks.
* Project which builds a Unity plugin package that can be used to redistribute
Parse's implementation of System.Threading.Tasks.
Unity 2017 adds experimental support for .NET 4.5 (upgrading from a partially
compatible version of .NET 3.5).  With .NET 4.5, the Parse Task implementation
is no longer required as System.Threading.Task is present in the .NET
framework.  For users distributing assemblies built against the Unity.Compat.dll
and Unity.Tasks.dll components, this results in Unity failing to compile
assemblies when .NET 4.5 is selected due to duplicate implementations of
System.Threading.Tasks.
So for the .NET 4.5 configuration in Unity, the Unity.Tasks.dll assembly (built
by …
> Type forwarding DLL for the Parse Task implementation and Unity plugin

- Unity.Tasks/Public/TaskFactory.cs
Task.Run should run tasks on the threadpool but are instead run on SynchronizationContext.Current.
See: http://stackoverflow.com/questions/41959490/firebase-makes-tasks-execute-only-on-main-thread-causing-unity-to-freeze/41988539#41988539
Basically what's going on is that the TaskFactory defaults to the SynchronizationContext.Current scheduler, which is not correct as new tasks always should be run on the threadpool.  TaskScheduler.FromCurrentSynchronizationContext() is instead intended to be used with ContinueWith as a mechanism for controlling the thread that the callback will run on.  But adding that support is a new feature.
Supporting information:
MSDN Documentation that Task.Run should run on the threadpool:
https://www.google.com/url?q=https://msdn.microsoft.com/en-us/library/system …
> Task.Run should run tasks on the threadpool

- ParsePush/Internal/Android/ManifestInfo.cs
I tried to set up the gcm and because the guide (http://docs.parseplatform.org/parse-server/guide/#configuring-your-clients-to-receive-push-notifications) is a bit outdated and it had wrong permissions. But when using them the error message would show that the error messages are from the other group of permissions. Swapping the names would solve the problem and would show the correct permissions where the problem occurred.
Atm:
`bool hasApplicationPermission = hasPermissions(
"android.permission.INTERNET",
"android.permission.ACCESS_NETWORK_STATE",
"android.permission.WAKE_LOCK",
"android.permission.GET_ACCOUNTS",
"com.google.android.c2dm.permission.RECEIVE",
PackageName + ".permission.C2D_MESSAGE"
);`
gets checked and 
`(hasApplicationPermission ? "" : …
> Swap 2 error messages

- Parse.Test/ConversionTests.cs
- Parse/Internal/ParseCorePlugins.cs
- Parse/Public/ParseClient.cs
- Parse/Public/ParseObject.cs
- Parse/Public/Utilities/Conversion.cs
This PR adds invariant culture to the conversion methods used in Parse.
It prevents conversion based on a device's locale (e.g. french or german) to error on numbers encoded with invariant/US locale (which uses . instead of , as decimal delimiter).
In addition a test method is added (to check this method on the developers machine locale)
The test might be extended to explicitly use non-invariant locales for testing (e.g. german or french) to allow it to properly work on machines not using those locales by default. 
I'm not quite sure on what basis I should pick those locales to test again, except for those two I know of which caused the error described in issue #305. (Feedback is appreciated on this one)
This pull request handles issue #305
> Use invariant device locale for number format conversion

- README.md
Fix documentation regarding initializing the ParseClient
> Update documentation around initialization of ParseClient

- Parse/Parse.csproj
- README.md
This PR reverted the misguiding versioning string to include 'develop' again.
It also extends the getting started section by additional links to NuGet and the releases section to get people started without requiring them to build everything themselves.
> Revert develop state indication for v2.0.0

- .github/ISSUE_TEMPLATE/---1-report-an-issue.md
- .github/ISSUE_TEMPLATE/---2-feature-request.md
- .github/ISSUE_TEMPLATE/config.yml
- .github/stale.yml
Added issue templates as discussed [here](https://community.parseplatform.org/t/harmonize-github-labels-and-usage/583/11) with @TobiasPott.
This PR also includes a bot that marks issues as stale after 45 days of inactivity and closes them after additional 7 days. The bot does not act on issues with certain labels, see file `style.yml`.
The templates are the new ones we recently introduced in parse server and parse JS SDK. So this PR will also be beneficial when transferring issues between repos to have a consistent report format.
> added issue templates; added stale bot

- .github/workflows/release-automated.yml
- package-lock.json
- package.json
- release.config.js
The release workflow publishes the correct nuget version, but doesn't update the DLL file version. For example Parse 3.0.0 on nuget downloads the Parse.dll with version code 2.0.0. The DLL file is correct, but it's version is not updated correctly. That means the nuget installs the correct Parse.dll file, just the file itself shows an incorrect version, so we won't unpublish the nuget version 3.0.0.
> ci: Fix incorrect DLL version on release

- Parse.Tests/AnalyticsTests.cs
- Parse.Tests/CloudControllerTests.cs
- Parse.Tests/CloudTests.cs
- Parse.Tests/ConfigTests.cs
- Parse.Tests/InstallationTests.cs
- Parse.Tests/ObjectTests.cs
- Parse.Tests/ProgressTests.cs
- Parse.Tests/UserTests.cs
- Parse/Infrastructure/Execution/UniversalWebClient.cs
- Parse/Platform/Users/ParseUser.cs
Fixed an issue Parse LogoutAsync's test would not pass. 
Closes #400 
Now All user tests so far pass hopefully better coverage too.;
> fix: `Parse.ParseUser.LogOutAsync` optimization

- Parse.Tests/EncoderTests.cs
- Parse.Tests/RelationTests.cs
- Parse/Abstractions/Infrastructure/IJsonConvertible.cs
- Parse/Infrastructure/Control/ParseAddOperation.cs
- Parse/Infrastructure/Control/ParseAddUniqueOperation.cs
- Parse/Infrastructure/Control/ParseDeleteOperation.cs
- Parse/Infrastructure/Control/ParseIncrementOperation.cs
- Parse/Infrastructure/Control/ParseRelationOperation.cs
- Parse/Infrastructure/Control/ParseRemoveOperation.cs
- Parse/Infrastructure/Control/ParseSetOperation.cs
- Parse/Infrastructure/Execution/ParseCommandRunner.cs
- Parse/Infrastructure/Execution/UniversalWebClient.cs
- Parse/Platform/Configuration/ParseConfiguration.cs
- Parse/Platform/Configuration/ParseCurrentConfigurationController.cs
- Parse/Platform/Files/ParseFile.cs
- Parse/Platform/Location/ParseGeoPoint.cs
- Parse/Platform/Relations/ParseRelation.cs
- Parse/Platform/Security/ParseACL.cs
This PR aims at fixing only Parse Relations and its related operations (Add, Set, etc..)
- Changed the return time of `ConvertToJSON` to return "object" as we now use that one method to pass both primitive and complex datatypes like Dictionnary for Relations.
- Implemented `ConvertToJSON `in ParseRelationOperations which now fixes Relations completely (Before, the related object would save but its pointer was never referenced)
- Removed `Encode()` as `ConvertToJSON` is now the method called.
- Added Unit Tests.
- Closes #404
> fix: `ParseObject` Relations not working
